default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: invoices_api_test

production:
  primary: &primary_production
    <<: *default
    database: invoices_api_production
    username: invoices_api
    password: <%= ENV["DB_NAME"] %>
  cache:
    <<: *primary_production
    database: invoices_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: invoices_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: invoices_api_production_cable
    migrations_paths: db/cable_migrate
